# Generated by Django 3.2.3 on 2021-07-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_point_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point_table',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.team'),
        ),
    ]
