# Generated by Django 3.2.3 on 2021-07-08 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210705_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(default='+91', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
